// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-yBOb5V6Hbz08anQtcSF7PA44-628BxI',
    appId: '1:98857141209:web:786505be075a9739310fc8',
    messagingSenderId: '98857141209',
    projectId: 'yellowbook-cac85',
    authDomain: 'yellowbook-cac85.firebaseapp.com',
    storageBucket: 'yellowbook-cac85.firebasestorage.app',
    measurementId: 'G-CJC7R4DR24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXhFwRcBPiMkKFhrpveI39SEQNFmD1cm4',
    appId: '1:98857141209:android:359927fb2309e9be310fc8',
    messagingSenderId: '98857141209',
    projectId: 'yellowbook-cac85',
    storageBucket: 'yellowbook-cac85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg5NlYpbzy5-4tEX7dPU8NIIugNPx8UgE',
    appId: '1:98857141209:ios:cf9cca427354d384310fc8',
    messagingSenderId: '98857141209',
    projectId: 'yellowbook-cac85',
    storageBucket: 'yellowbook-cac85.firebasestorage.app',
    iosBundleId: 'com.example.entertainer',
  );
}
